### ISSUE TITLE
run.sh results in connection error

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/scrypt-interactive#18]
Can't run tests since new change this morning on osx or ubuntu. Tried different ipc paths on mac and no luck.

Here is the error:

```
(node:12341) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: CONNECTION ERROR: Couldn't connect to node on IPC.
(node:12341) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by terminaldweller** [comment]
the node script expects to get an arg for the geth.ipc path like this:
`node ./test/index.js /tmp/ethereum_dev_mode/geth.ipc`
if you don't provide one, the ipcpath will be the address of index.js, hence the error.

**Comment by hswick** [comment]
Sweet, that worked.

**Comment by terminaldweller** [comment]
the run script will pass its first argument to node, so you can use that too.

**Comment by hswick** [comment]
Yeah

```
./run.sh /tmp/ethereum_dev_mode/geth.ipc
```

Worked for me.
