### ISSUE TITLE
claimDecided can get the ClaimManager contract stuck

### ISSUE THREAD

**Issue by sinahab** [TrueBitFoundation/scrypt-interactive#23]
Iterating over all challengers to unbond their deposits can get the contract struck. 

As per @chriseth [comments](https://github.com/sinahab/scrypt-interactive/commit/6283bb7999bbb3ecb2445a18233e1a0543a1e39c#diff-9ad04a1789800dfd16b0fb34220b0e84R129).

**Comment by hswick** [comment]
Fixed with https://github.com/TrueBitFoundation/scrypt-interactive/pull/24/commits/e65afea253a7e189a99f3587c401208186cd3edc in sina's branch.
