### ISSUE TITLE
Modify travis.yml to use new tests

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/scrypt-interactive#25]
Currently travis.yml is looking for test_manual directory which no longer exists

**Comment by hswick** [comment]
@bloodstalker could you take a look at this?

**Comment by terminaldweller** [comment]
sure, let me take a look.

**Comment by terminaldweller** [comment]
how do you wanna do the tests on travis?
with or without travis?
you wanna use testrpc, geth or ganache?
if the answer is ganache + truffle, just running `run.sh` will do it.

**Comment by hswick** [comment]
Ideally using geth with ability to overcome gas issue when doing a call on getStateProofAndHash. So if it could run the tests in tests that would be awesome!

**Comment by terminaldweller** [comment]
with or without truffle?

**Comment by hswick** [comment]
truffle would be nice
