### ISSUE TITLE
Set minDeposit for claimant/challenger

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/scrypt-interactive#26]
Each claimant/challenger puts up a minDeposit to be bonded. What should the value be?

Possible option:

minDeposit = 2 x (network fees + gas)

Cyrptoeconomic considerations:
Burn 60% of tokens when claimant loses –– so they can’t keep challenging themselves and delay the game forever.

**Comment by hswick** [comment]
minDeposit currently set to 1

**Comment by sinahab** [comment]
Following up on discussions with Oscar, this should be set to `0.001 ETH`
