### ISSUE TITLE
bondDeposit needs to check if claim exists

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/scrypt-interactive#29]
bondDeposit: check whether the claim exists before proceeding. this prevents the case where another agent has already submitted the same claim

**Comment by sinahab** [comment]
This is referring to `bondDeposit` in the `claimManager.sol` contract:  https://github.com/TrueBitFoundation/scrypt-interactive/pull/24#discussion_r153280702

We might need to add similar checks in other functions.
