### ISSUE TITLE
Use a pull, instead of push, model for unbonding deposits

### ISSUE THREAD

**Issue by sinahab** [TrueBitFoundation/scrypt-interactive#42]
Instead of the contract unbonding user deposits automatically, it should allow users to call a function to unbond their own deposits.

Two places where this change needs to be implemented:

1) in `claimDecided` function of the `claimManager` contract, when `claim.claimant == loser` and all challenger deposits are unbonded.

2) in `checkClaimDecided` function of the `claimManager` contract, when the claimant's deposit is unbonded.

**Comment by shrugs** [comment]
What's the motivation for this change?

**Comment by chriseth** [comment]
The number of challengers is unbounded, so the contract might get stuck because of gas costs higher than the block gas limit.

**Comment by teutsch** [comment]
Interesting.

**Comment by hswick** [comment]
This was fixed in latest PR.
