### ISSUE TITLE
Modify the geth client to have a higher timeout.

### ISSUE THREAD

**Issue by sinahab** [TrueBitFoundation/scrypt-interactive#43]
Modify the geth Ethereum client to have a higher timeout.

Reason: so we can run Scrypt locally.

The change will likely happen in [this line of eth/api.go](https://github.com/ethereum/go-ethereum/blob/master/eth/api.go#L502).

This is already implemented in the `scrypt-interactive` travis script.

Our plan going forward for scrypt-interactive clients is to either:
a) run a modified version of geth with the increased time-out.
b) hopefully get the go-ethereum team to add an ability to set the timeout via a command line parameter.

**Comment by hswick** [comment]
Using parity dev chain instead
