### ISSUE TITLE
Use Events only for notifying of updates; all state should be accessible in the contract.

### ISSUE THREAD

**Issue by sinahab** [TrueBitFoundation/scrypt-interactive#46]
Reasoning: a client can go offline due to network problems. Upon coming back online, it should be able to reconstruct it's world-view, and know what it needs to do as a next step, using state accessors on the contract.

We specifically need the following pieces:

* the client needs to be able to find out which claims they have challenged, and where they have bonded deposits. Perhaps add a function to claimManager that returns all claims in which an address has bonded deposits?

**Comment by hswick** [comment]
This is same as #28

**Comment by chriseth** [comment]
#28 should only be a part of it, it has to be possible to reconstruct the internal state of the off-chain client only by calling view functions.
