### ISSUE TITLE
Allow anyone to call checkScrypt on ClaimManager

### ISSUE THREAD

**Issue by sinahab** [TrueBitFoundation/scrypt-interactive#72]
`ClaimManager#checkScrypt` will allow anyone to verify a value is the correct Scrypt hash of some plaintext.

This involves some changes to `ClaimManager#checkScrypt`:

1) Remove the `onlyBy(dogeRelay)` modifier.
2) Remove `claimant` as a function parameter.
3) Add `callbackContract` (a contract which implements the `scryptVerified` interface) as a function parameter.
4) In the body: set `claim.claimant` to `tx.origin`. This fits our functionality: 1) anyone can call the function directly, becoming the claimant. 2) the SubmitterAgent can call the DogeRelay via `storeBlockHeader` which makes an internal call to `checkScrypt`; in this case, the SubmitterAgent is correctly set as the claimant.
5) In the body: set `claim.callbackContract` as the provided address in the function call. Later, when the claim resolves, callback to this contract. This allows flexibility in anyone using the Truebit scrypt verification system.

**Comment by sinahab** [comment]
@hswick @Shrugs @mrsmkl – following up on our discussion. Thoughts?

@oscarguindzberg – fyi

**Comment by shrugs** [comment]
Also remove anything relevant to the dogeRelay itself (address storage, `setDogeRelay()`, etc).
